Repository Hackiflette/BlackJackProject, pull requests merged in 2019-09, with the labels that each got.

#29 resize tokens and add alpha
  data/config/tokens.cfg.json
  data/pictures/tokens/token_black.jpg
  data/pictures/tokens/token_black.png
  data/pictures/tokens/token_blue.jpg
  data/pictures/tokens/token_blue.png
  data/pictures/tokens/token_green.jpg
  data/pictures/tokens/token_green.png
  data/pictures/tokens/token_red.jpg
  data/pictures/tokens/token_red.png
  data/pictures/tokens/token_white.jpg
  data/pictures/tokens/token_white.png
Labels: GUI, enhancement

#32 Load Images
  data/config/path.cfg.json
  main.py
  src/common/func_pictures.py
  src/controller/game_controller.py
  src/humans/dealer.py
  src/humans/player.py
  src/humans/tests/test_player.py
  src/tokens/__init__.py
  src/views/card_area_organizer.py
  src/views/image_loaders/__init__.py
  src/views/image_loaders/cardsloader.py
  src/views/image_loaders/tokensloader.py
  src/views/view_game.py
Labels: GUI

#34 Buttons event
  src/button/button.py
  src/button/tests/test_button.py
  src/controller/game_controller.py
  src/views/view_game.py
  src/views/view_menu.py
Labels: BackEnd, GUI, enhancement
